server:
  port: 8090
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/sales?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 906342347441-55krhplkfa2v2iv3rldf00n0ar6utvkj.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile